# Use postgres/example user/password credentials
version: '3.1'

#services:
#
#  db:
#    image: postgres
#    restart: always
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_PASSWORD: sifre123
#
spring:
  datasource:
    username: postgres
    password: benimSifrem
    url: jdbc:postgresql://localhost:5432/demo

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081



